spring:
  profiles.active: development
---
spring:
  profiles: development
  application:
    name: populator
  datasource:
    url: jdbc:mysql://PATH_TO_DATABASE?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: USERNAME
    password: PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
services:
  extractor:
    address: http://localhost:5000